### ISSUE TITLE
/bin/bash: ./darknet: Is a directory

### ISSUE THREAD

**Issue by aakarsh1011** [pjreddie/darknet#2141]
I am training the Yolov_3 using AlexeyAB darknet framework. I have used 2 classes and changed the cfg by replacing Yolo `classes = 2` and `filters = 35` using the formula `(classes + 5)*5`.
I have downloaded the predefined weights using:
`!wget http://pjreddie.com/media/files/darknet53.conv.74`
While starting the training using `! ./darknet detector train data/obj.data cfg/yolov3_custom2.cfg darknet53.conv.74` it displays:
`/bin/bash: ./darknet: Is a directory`. I am performing the training on Google Colab.
![Screenshot (78)](https://user-images.githubusercontent.com/37743882/81177329-16f8fd80-8fc4-11ea-99b4-270484ec600f.png). Kindly help me out.

**Comment by aakarsh1011** [comment]
The mistake was, there were two folders with name `data` in the darknet directory

**Comment by cvrattos1** [comment]
How did you end up fixing this issue? Did you run a different command?

**Comment by aakarsh1011** [comment]
> How did you end up fixing this issue? Did you run a different command?

I manually transferred everything from one 'data folder to another data(main) folder' and deleted the former one.

**Comment by aishwarya2905** [comment]
I do not have folders with same name in the darknet directory, yet I'm facing this issue

**Comment by farahqoonita** [comment]
hey im facing the same problem, but it doesnt work :((

**Comment by Shrikant3542** [comment]
@aishwarya2905 any update on ur issue.

**Comment by alsheabi** [comment]
I faced this issue and solved by run this "!make" if u work on colab. or install make and cmake on your local machine and run !make

**Comment by rohittechzone** [comment]
> I do not have folders with same name in the darknet directory, yet I'm facing this issue.
> 
> Edit: Got the solution. There is a darknet file inside the darknet directory which you need to use and you need to give that darknet file's path(not the directory's path).
> './darknet detector train...' works when you are inside the darknet directory, else give the entire path to the darknet file.
> Try using ./darknet/darknet

Thanks this worked by also changing the  path of some variables in obj.names

**Comment by DarkCharade** [comment]
> I do not have folders with same name in the darknet directory, yet I'm facing this issue.
> 
> Edit: Got the solution. There is a darknet file inside the darknet directory which you need to use and you need to give that darknet file's path(not the directory's path).
> './darknet detector train...' works when you are inside the darknet directory, else give the entire path to the darknet file.
> Try using ./darknet/darknet

You said there is a darknet file inside the darknet directory that we need to use but you didn't name that file . is it the darknet.py ? 
I have it there and I still encounter the same problem.

**Comment by rohittechzone** [comment]
No it's a folder in it

**Comment by aishwarya2905** [comment]
> > I do not have folders with same name in the darknet directory, yet I'm facing this issue.
> > Edit: Got the solution. There is a darknet file inside the darknet directory which you need to use and you need to give that darknet file's path(not the directory's path).
> > './darknet detector train...' works when you are inside the darknet directory, else give the entire path to the darknet file.
> > Try using ./darknet/darknet
> 
> You said there is a darknet file inside the darknet directory that we need to use but you didn't name that file . is it the darknet.py ?
> I have it there and I still encounter the same problem.

No, the filename is "darknet" which will be generated after you execute the "make" command. It has no extension. Please refer the attached image.
![darknet_folder](https://user-images.githubusercontent.com/54367237/109411703-faeaa080-79c9-11eb-9c8c-aa07236962d5.JPG)

**Comment by DarkCharade** [comment]
> > > I do not have folders with same name in the darknet directory, yet I'm facing this issue.
> > > Edit: Got the solution. There is a darknet file inside the darknet directory which you need to use and you need to give that darknet file's path(not the directory's path).
> > > './darknet detector train...' works when you are inside the darknet directory, else give the entire path to the darknet file.
> > > Try using ./darknet/darknet
> > 
> > 
> > You said there is a darknet file inside the darknet directory that we need to use but you didn't name that file . is it the darknet.py ?
> > I have it there and I still encounter the same problem.
> 
> @DarkCharade
> No, the filename is "darknet" which will be generated after you execute the "make" command. It has no extension. Please refer the attached image.
> ![darknet_folder](https://user-images.githubusercontent.com/54367237/109411703-faeaa080-79c9-11eb-9c8c-aa07236962d5.JPG)

Solved thanks. I didn't have the make command in the colab file. After executing !make command the darknet file was there and the training started

**Comment by cengsemihsahin** [comment]
If you work on colab, pls run '!cmake' command.

**Comment by greesh02** [comment]
even after using !make in github the darknet file is not generated what can i do??

**Comment by flurpo** [comment]
/bin/bash: darknet/darknet: No such file or directory

Yet I see the darknet directory with the darknet file.....Trying to run in colab   !darknet/darket detector train """

Help

**Comment by aishwarya2905** [comment]
> Yet I see the darknet directory with the darknet file.....Trying to run in colab !darknet/darket detector train """

I see a spelling error in the **darknet** filename.  If that isn't the case, make sure you have given the path to the darknet file correctly. Check if the folder you are in, contains the darknet folder(You can use the !ls commend to check this in colab notebook) If you are inside the darknet directory, then the colab command just shoud be "!./darknet detector train"

**Comment by jestinmwilson** [comment]
im still facing the problem any update?

**Comment by notinrange** [comment]
How to solve this issue without using !make command ?

**Comment by JeffVu-1** [comment]
> even after using !make in colab the darknet file is not generated what can i do??

ik this is a late reply but how'd you ifix this issue? as im also missing that file

**Comment by notinrange** [comment]
Unistall and reinstall using pip

**Comment by JeffVu-1** [comment]
> Unistall and reinstall using pip

Reinstall which pip? I’m running this off of Google colab as well.

**Comment by notinrange** [comment]
then start whole code with different google id or try with different versons of library

**Comment by leofab** [comment]
> > > I do not have folders with same name in the darknet directory, yet I'm facing this issue.
> > > Edit: Got the solution. There is a darknet file inside the darknet directory which you need to use and you need to give that darknet file's path(not the directory's path).
> > > './darknet detector train...' works when you are inside the darknet directory, else give the entire path to the darknet file.
> > > Try using ./darknet/darknet
> > 
> > 
> > You said there is a darknet file inside the darknet directory that we need to use but you didn't name that file . is it the darknet.py ?
> > I have it there and I still encounter the same problem.
> 
> @DarkCharade No, the filename is "darknet" which will be generated after you execute the "make" command. It has no extension. Please refer the attached image. ![darknet_folder](https://user-images.githubusercontent.com/54367237/109411703-faeaa080-79c9-11eb-9c8c-aa07236962d5.JPG)

For me, as i was in Colab, i had to import cv2 after running !make, now its working fine
